### ISSUE TITLE
AssertionError: Inconsistent state: has_parent=False, has_rank=True

### ISSUE THREAD

**Issue by wojiaoyanmin** [saic-mdal/lama#120]
multi-machine,multi-gpu:

2022-05-21 09:28:21.116 [ERROR] Traceback (most recent call last):
2022-05-21 09:28:21.116 [ERROR]   File "/root/share/program/lama-main/bin/train.py", line 76, in <module>
2022-05-21 09:28:21.116 [ERROR]     main()
2022-05-21 09:28:21.117 [ERROR]   File "/root/share/program/lama-main/saicinpainting/utils.py", line 154, in new_main
2022-05-21 09:28:21.177 [ERROR]     assert has_parent == has_rank, f'Inconsistent state: has_parent={has_parent}, has_rank={has_rank}'
2022-05-21 09:28:21.177 [ERROR] AssertionError: Inconsistent state: has_parent=False, has_rank=True
2022-05-21 09:28:21.608 [ERROR] Traceback (most recent call last):
2022-05-21 09:28:21.609 [ERROR]   File "/opt/aps/context/run.py", line 43, in <module>
2022-05-21 09:28:21.609 [ERROR]     exec_code(cell_code,i)
2022-05-21 09:28:21.609 [ERROR]   File "/opt/aps/context/run.py", line 35, in exec_code
2022-05-21 09:28:21.610 [ERROR]     exec(code, globals)
2022-05-21 09:28:21.610 [ERROR]   File "1 cell", line 4, in <module>
2022-05-21 09:28:21.654 [ERROR] Exception: exec failed
2022-05-21 09:28:21.655 [ERROR] 
2022-05-21 09:28:21.655 [ERROR] During handling of the above exception, another exception occurred:
2022-05-21 09:28:21.656 [ERROR] 
2022-05-21 09:28:21.656 [ERROR] Traceback (most recent call last):
2022-05-21 09:28:21.657 [ERROR]   File "/opt/aps/context/run.py", line 45, in <module>
2022-05-21 09:28:21.657 [ERROR]     raise ExecutionError(sys.exc_info())
2022-05-21 09:28:21.658 [ERROR] __main__.ExecutionError: (<class 'Exception'>, Exception('exec failed'), <traceback object at 0x7fad01b89e10>)
2022-05-21 09:28:21,787 [ERROR] exit code is 1
root@dl-1655299666-pod-jupyter-6dd949c6b4-tgf65:~/.dllog/2022-05/ZITS_20220521092748# 

how to fix this?

**Comment by LonglongaaaGo** [comment]
> multi-machine,multi-gpu:
> 
> 2022-05-21 09:28:21.116 [ERROR] Traceback (most recent call last): 2022-05-21 09:28:21.116 [ERROR] File "/root/share/program/lama-main/bin/train.py", line 76, in 2022-05-21 09:28:21.116 [ERROR] main() 2022-05-21 09:28:21.117 [ERROR] File "/root/share/program/lama-main/saicinpainting/utils.py", line 154, in new_main 2022-05-21 09:28:21.177 [ERROR] assert has_parent == has_rank, f'Inconsistent state: has_parent={has_parent}, has_rank={has_rank}' 2022-05-21 09:28:21.177 [ERROR] AssertionError: Inconsistent state: has_parent=False, has_rank=True 2022-05-21 09:28:21.608 [ERROR] Traceback (most recent call last): 2022-05-21 09:28:21.609 [ERROR] File "/opt/aps/context/run.py", line 43, in 2022-05-21 09:28:21.609 [ERROR] exec_code(cell_code,i) 2022-05-21 09:28:21.609 [ERROR] File "/opt/aps/context/run.py", line 35, in exec_code 2022-05-21 09:28:21.610 [ERROR] exec(code, globals) 2022-05-21 09:28:21.610 [ERROR] File "1 cell", line 4, in 2022-05-21 09:28:21.654 [ERROR] Exception: exec failed 2022-05-21 09:28:21.655 [ERROR] 2022-05-21 09:28:21.655 [ERROR] During handling of the above exception, another exception occurred: 2022-05-21 09:28:21.656 [ERROR] 2022-05-21 09:28:21.656 [ERROR] Traceback (most recent call last): 2022-05-21 09:28:21.657 [ERROR] File "/opt/aps/context/run.py", line 45, in 2022-05-21 09:28:21.657 [ERROR] raise ExecutionError(sys.exc_info()) 2022-05-21 09:28:21.658 [ERROR] **main**.ExecutionError: (<class 'Exception'>, Exception('exec failed'), <traceback object at 0x7fad01b89e10>) 2022-05-21 09:28:21,787 [ERROR] exit code is 1 root@dl-1655299666-pod-jupyter-6dd949c6b4-tgf65:~/.dllog/2022-05/ZITS_20220521092748#
> 
> how to fix this?

Hi, did you solve this problem?

**Comment by Abbsalehi** [comment]
did you find a solution?

**Comment by buptlj** [comment]
same problem

**Comment by Abbsalehi** [comment]
> same problem

Are you using Slurm based HPC?
