### ISSUE TITLE
Training failed due to You are trying to `self.log()` but it is not managed by the `Trainer` control flow: Traceback (most recent call last):  

### ISSUE THREAD

**Issue by LonglongaaaGo** [saic-mdal/lama#130]
Hi, @senya-ashukha Thanks for your awesome work！

Could you give any ideas for solving this bug?

Traceback (most recent call last):
  File ".//train-slurm.py", line 76, in main
    trainer.fit(training_model)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 246, in advance
    self.trainer._logger_connector.update_train_step_metrics()
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 174, in update_train_step_metrics
    self._log_gpus_metrics()
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 202, in _log_gpus_metrics
    self.trainer.lightning_module.log(
  File "/home/longlong/n_pt1.7/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 387, in log
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You are trying to `self.log()` but it is not managed by the `Trainer` control flow

**Comment by senya-ashukha** [comment]
Hi @LonglongaaaGo ! Thanks for the kind words!

I have resigned recently, @windj007 can you possibly look?

**Comment by LonglongaaaGo** [comment]
> Hi @LonglongaaaGo ! Thanks for the kind words!
> 
> I have resigned recently, @windj007 can you possibly look?

Hi @senya-ashukha , Thank you for your reply.
I have solved this problem by using the recommended Pytorch-lightning version. 
Have a good day!
