### ISSUE TITLE
Prediction failed due to invalid signal value

### ISSUE THREAD

**Issue by remictrr** [saic-mdal/lama#150]
I try to implement lama in a personal project, but i'm having trouble running it. I'm using windows (i hope this is not the issue) and venv.
I installed all the dependencies (at least i think, because there are no more "module not installed" errors), but when i run the following command : `python3 bin/predict.py ` (I don't use the model and in/out directories parameters because i overrited those in the configs/default.yaml file)

I get the following error:
`[2022-08-14 14:51:37,635][saicinpainting.utils][WARNING] - Setting signal 1 handler <function print_traceback_handler at 0x000002EB839A8C80>
[2022-08-14 14:51:37,637][__main__][CRITICAL] - Prediction failed due to invalid signal value:
Traceback (most recent call last):
  File "bin/predict.py", line 41, in main
  File "C:\Users\remic\Documents\storage\python\projects\PIL\layers extractor\venv\lib\site-packages\saicinpainting\utils.py", line 109, in register_debug_signal_handlers
    signal.signal(sig, handler)
  File "C:\Users\remic\Documents\storage\python\versions\3.7.0\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: invalid signal value`

I have no idea on what's causing the issue and how to solve it, but if someone know what's happening, i would be very grateful (even if it's just a small hint)

**Comment by remictrr** [comment]
thanks, it worked !
You saved my project
