### ISSUE TITLE
predict.py error 

### ISSUE THREAD

**Issue by aibohang** [saic-mdal/lama#193]
![image](https://user-images.githubusercontent.com/45119898/206707194-af2f78d5-7fbb-490d-aa5c-2cccc8e6cc73.png)
**  warn(f"Failed to load image Python extension: {e}")
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
Detectron v2 is not installed
Traceback (most recent call last):
  File "G:\Compiler\Anaconda2021.11\envs\cu102_torch110_py38_lama\lib\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "G:\Compiler\Anaconda2021.11\envs\cu102_torch110_py38_lama\lib\site-packages\hydra\_internal\utils.py", line 333, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File "G:\Compiler\Anaconda2021.11\envs\cu102_torch110_py38_lama\lib\site-packages\hydra\_internal\hydra.py", line 64, in create_main_hydra2
    hydra = cls(task_name=task_name, config_loader=config_loader)
  File "G:\Compiler\Anaconda2021.11\envs\cu102_torch110_py38_lama\lib\site-packages\hydra\_internal\hydra.py", line 75, in __init__
    setup_globals()
  File "G:\Compiler\Anaconda2021.11\envs\cu102_torch110_py38_lama\lib\site-packages\hydra\core\utils.py", line 185, in setup_globals
    OmegaConf.register_new_resolver(
TypeError: register_new_resolver() got an unexpected keyword argument 'replace'
**
### **I meet this problem,please help me .thank you very much**

**Comment by cohimame** [comment]
Hello!

Could you check if you are using `hydra-core==1.1.0` version:

```
(inpenv):~/projects$ python
>>> import hydra
>>> hydra.__version__
'1.1.0'
```

**Comment by titusfx** [comment]
@cohimame I've the same problem and yes my hydra version is 1.1.0 

and my error is :

Detectron v2 is not installed
LexerNoViableAltException: Vision/inpainting/lama/big-lama
                                                     ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

**Comment by titusfx** [comment]
I set the env var for a complete stack trace:

```bash
export TORCH_HOME=$(pwd) && export PYTHONPATH=$(pwd) && export HYDRA_FULL_ERROR=1
```
and then:

```bash
$ python3 bin/predict.py model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output
Detectron v2 is not installed
Traceback (most recent call last):
  File "bin/predict.py", line 103, in <module>
    main()
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/utils.py", line 371, in <lambda>
    overrides=args.overrides,
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 91, in run
    run_mode=RunMode.RUN,
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 568, in compose_config
    from_shell=from_shell,
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 150, in load_configuration
    from_shell=from_shell,
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 231, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home//anaconda3/envs/lama/lib/python3.6/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: LexerNoViableAltException: vision/inpainting/lama/big-lama
                                                     ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
```

**Comment by titusfx** [comment]
And I fix the problem in my path, it has a space on a folder:

`AI/computer vision/inpainting/lama$`

I change the foler name to `computer_vision`:

`AI/computer_vision/inpainting/lama$`

and it worked
