### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'generator' is not in struct

### ISSUE THREAD

**Issue by naoki7090624** [saic-mdal/lama#34]
Hi. Thank you for sharing your great work!!

I have a problem while I'm training the model on CelebA-HQ.
Could you please give me some advice?
 
```
python bin/train.py -cn lama-fourier-celeba data.batch_size=10
```

```
[2021-10-27 20:47:57,103][saicinpainting.utils][WARNING] - Setting signal 10 handler <function print_traceback_handler at 0x7f8d5ea940d0>
[2021-10-27 20:47:57,103][root][INFO] - Make training model default
[2021-10-27 20:47:57,104][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init called
[2021-10-27 20:47:57,104][root][INFO] - Make generator ffc_resnet
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/resolvers/__init__.py:12: UserWarning: The `env` resolver is deprecated, see https://github.com/omry/omegaconf/issues/573
  warnings.warn(
[2021-10-27 20:47:57,330][root][INFO] - Make discriminator pix2pixhd_nlayer
[2021-10-27 20:47:57,371][root][INFO] - Make visualizer directory
[2021-10-27 20:47:57,371][root][INFO] - Make evaluator default
[2021-10-27 20:47:58,532][saicinpainting.evaluation.losses.base_loss][INFO] - FIDscore init called
[2021-10-27 20:47:58,532][saicinpainting.evaluation.losses.fid.inception][INFO] - fid_inception_v3 called
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/torchvision/models/inception.py:81: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  warnings.warn('The default weight initialization of inception_v3 will be changed in future releases of '
[2021-10-27 20:47:58,894][saicinpainting.evaluation.losses.fid.inception][INFO] - models.inception_v3 done
[2021-10-27 20:47:59,008][saicinpainting.evaluation.losses.fid.inception][INFO] - fid_inception_v3 patching done
[2021-10-27 20:47:59,047][saicinpainting.evaluation.losses.fid.inception][INFO] - fid_inception_v3 weights downloaded
[2021-10-27 20:47:59,128][saicinpainting.evaluation.losses.fid.inception][INFO] - fid_inception_v3 weights loaded into model
[2021-10-27 20:47:59,136][saicinpainting.evaluation.losses.base_loss][INFO] - FIDscore init done
[2021-10-27 20:48:00,440][saicinpainting.evaluation.evaluator][INFO] - <class 'saicinpainting.evaluation.evaluator.InpaintingEvaluatorOnline'> init called
[2021-10-27 20:48:00,441][saicinpainting.evaluation.evaluator][INFO] - <class 'saicinpainting.evaluation.evaluator.InpaintingEvaluatorOnline'> init done
[2021-10-27 20:48:00,441][root][INFO] - Make evaluator default
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'lama-fourier-celeba': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'hydra/overrides': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'trainer/any_gpu_large_ssim_ddp_final_celeba': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'evaluator/default_inpainted': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'visualizer/directory': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'discriminator/pix2pixhd_nlayer': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'generator/ffc_resnet_075': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'data/abl-04-256-mh-dist-celeba': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'location/celeba': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
[2021-10-27 20:48:00,748][__main__][CRITICAL] - Training failed due to Key 'generator' is not in struct
    full_key: optimizers.generator
    object_type=dict:
Traceback (most recent call last):
  File "bin/train.py", line 64, in main
    trainer.fit(training_model)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu.py", line 30, in setup
    return super().setup(trainer, model)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in setup
    self.setup_optimizers(trainer)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 315, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in init_optimizers
    return trainer.init_optimizers(model)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/mnt/naoki/saicinpainting/training/trainers/base.py", line 120, in configure_optimizers
    dict(optimizer=make_optimizer(self.generator.parameters(), **self.config.optimizers.generator)),
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 166, in _validate_get
    self._format_and_raise(
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'generator' is not in struct
    full_key: optimizers.generator
    object_type=dict
```

**Comment by naoki7090624** [comment]
Thank you for your help.

I'm sorry. It may be due to my environment settings. The training code worked by using your Dockefile.
