### ISSUE TITLE
ValueError: `val_check_interval` (25000) must be less than or equal to the number of the training batches (3006)

### ISSUE THREAD

**Issue by naoki7090624** [saic-mdal/lama#64]
Thank you for sharing your great work!!

When I ran train.py with my own dataset, I got the following error.

```
[2021-12-07 11:28:26,947][__main__][CRITICAL] - Training failed due to `val_check_interval` (25000) must be less than or equal to the number of the training batches (3006). If you want to disable validation set `limit_val_batches` to 0.0 instead.:
Traceback (most recent call last):
  File "/home/naoki/lama/bin/train.py", line 64, in main
    trainer.fit(training_model)
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 620, in run_train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/training_loop.py", line 218, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/home/naoki/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py", line 243, in reset_train_dataloader
    raise ValueError(
ValueError: `val_check_interval` (25000) must be less than or equal to the number of the training batches (3006). If you want to disable validation set `limit_val_batches` to 0.0 instead.
```

My dataset consists of the following number of images.
* Train: 12022
* val_source: 2068
* visual_test_source: 188
* eval_source: 2032

Is this due to having too few training images?

**Comment by cohimame** [comment]
Hi!
Thank you for appreciation of our work!

> [2021-12-07 11:28:26,947][__main__][CRITICAL] - Training failed due to `val_check_interval` (25000) must be less than or equal to the number of the training batches (3006). If you want to disable validation set `limit_val_batches` to 0.0 instead.:

With the current batch_size and 12022 train images our training procedure produces 3006 training batches. While we ask it to perform validation after every 25000 batch in epoch. 

The simplest way to fix this error is to open 
`lama/configs/training/trainer/any_gpu_large_ssim_ddp_final.yaml `
and edit following parameters:
```
# @package _group_
kwargs:
  ...
  limit_train_batches: 3006 # <- was 25000
  val_check_interval: 3006 # or less, before it was ${trainer.kwargs.limit_train_batches}
```

**Comment by naoki7090624** [comment]
Thank you for quick response!!

I edited these parameters and ran it again. 
```
# @package _group_
kwargs:
  ...
  limit_train_batches: 3006
  val_check_interval: 3006
```
But I got the following error.
```
ValueError: `val_check_interval` (3006) must be less than or equal to the number of the training batches (1203). If you want to disable validation set `limit_val_batches` to 0.0 instead.
```
Therefore, I edit to ```val_check_interval: 1203```  and it worked fine.

I am concerned if there are appropriate parameters. How can I calculate the appropriate ```limit_train_batches``` and ```val_check_interval```?

**Comment by cohimame** [comment]
Hello!
Sorry for the late answer!

Suppose, we have 10000 images training dataset, 2 GPU's and a batch_size=5 images per GPU (in .yaml config we define batch_size per GPU). Then: 
```
total_batch_size == 10 (2 gpu x 5 imgs)
train_batches == 1000 (10000 imgs / total_batch_size)

limit_train_batches <= 1000
val_check_interval <=1000
```

**Comment by naoki7090624** [comment]
I got it! Thank you!!
